#ifndef GENERATED_CONSTANTS_H
#define GENERATED_CONSTANTS_H

#include <map>
#include <boost/variant.hpp>

std::map<int, boost::variant<int, float, bool, std::string>> constantMap = {
    {1, boost::variant<int, float, bool>(-1)},
    {2, boost::variant<int, float, bool>(23)},
    {4, boost::variant<int, float, bool>(false)},
    {5, boost::variant<int, float, bool>(23)},
    {6, boost::variant<int, float, bool>(-1)},
    {7, boost::variant<int, float, bool>(34)},
    {10, boost::variant<int, float, bool>(3)},
    {11, boost::variant<int, float, bool>(2)},
    {12, boost::variant<int, float, bool>(-30)},
    {16, boost::variant<int, float, bool>(23.8f)},
    {17, boost::variant<int, float, bool>(23)},
    {19, boost::variant<int, float, bool>(-23.8f)},
    {20, boost::variant<int, float, bool>(23)},
    {22, boost::variant<int, float, bool>(true)},
    {23, boost::variant<int, float, bool>(1)},
    {24, boost::variant<int, float, bool>(1)},
    {25, boost::variant<int, float, bool>(false)},
    {26, boost::variant<int, float, bool>(234)},
    {27, boost::variant<int, float, bool>(23)},
    {30, boost::variant<int, float, bool>(34)},
    {31, boost::variant<int, float, bool>(2)},
    {33, boost::variant<int, float, bool>(1)},
    {34, boost::variant<int, float, bool>(2)},
    {36, boost::variant<int, float, bool>(3423)},
    {38, boost::variant<int, float, bool>(234)},
    {39, boost::variant<int, float, bool>(23)},
    {42, boost::variant<int, float, bool>(34)},
    {43, boost::variant<int, float, bool>(2)},
    {45, boost::variant<int, float, bool>(true)},
    {46, boost::variant<int, float, bool>(234)},
    {47, boost::variant<int, float, bool>(23)},
    {50, boost::variant<int, float, bool>(34)},
    {51, boost::variant<int, float, bool>(2)},
    {53, boost::variant<int, float, bool>(10)},
    {55, boost::variant<int, float, bool>(1)},
    {57, boost::variant<int, float, bool>(23)},
    {58, boost::variant<int, float, bool>(2.2f)},
    {59, boost::variant<int, float, bool>(3)},
    {60, boost::variant<int, float, bool>(23)},
    {62, boost::variant<int, float, bool>(33.3f)},
    {64, boost::variant<int, float, bool>(1)},
    {66, boost::variant<int, float, bool>(1)},
    {68, (std::string) ("asdlkfja;sdlkfj  a;skd oowrasdfasdn")},
    {69, (std::string) ("asdlkfja;sdlkfj  a;skd oowdsaasdffrn")},
    {70, (std::string) ("asdlkfja;sdlkfj  a;skd oowrnsdssd")},
    {71, (std::string) ("asdlkfja;sdlkfj  a;skd oowrndsd")},
    {72, (std::string) ("asdlkfja;sdlkfj  a;skd oowrndsd")},
    {73, (std::string) (" ")},
};

#endif // GENERATED_CONSTANTS_H
